
{{- range $name, $app := .Values.applications -}}
{{ if .enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ default $name .name }}
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: {{ default $name .name }}-{{ .env }}
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
  - '*'

{{ printf "---" }}
{{- end }}
{{- end }}
