
{{- range $App := .Values.Applications }}

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .appName }}-{{ .env }}
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: {{ .appName }}-{{ .env }}
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
  - '*'

{{ printf "---" }}
{{- end }}
