{{- range $name, $app := .Values.applications -}}
{{ if .enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ default $name .name }}-{{ .env }}
  labels:
    name: {{ default $name .name }}-{{ .env }}
    goldilocks.fairwinds.com/enabled: "true"

{{ printf "---" }}
{{- end }}
{{- end }}
