{{- range $App := .Values.Applications }}

{{- if .enableNetworkPolicy }}

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny.all
  namespace: {{ .appName }}-{{ .env }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow.same.namespace
  namespace: {{ .appName }}-{{ .env }}
spec:
  podSelector: {}
  ingress:
  - from:
    - podSelector: {}
  policyTypes:
  - Ingress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow.kube.system
  namespace: {{ .appName }}-{{ .env }}
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    - namespaceSelector:
        matchLabels:
          name: argocd
  policyTypes:
  - Ingress

{{ printf "---" }}
{{- end }}
{{- end }}
